### ISSUE TITLE
Quotes not working

### ISSUE THREAD

**Issue by bnason** [lucasepe/yo#3]
Trying out the example in the readme for dealing with spaces and quotes

```sh
$ yo fullName="Scarlett Johansson" age=36 hot=true
```

generates...

```yaml
age: 36
fullName: Scarlett
hot: true
```

While it should generate

```yaml
age: 36
fullName: Scarlett Johansson
hot: true
```
